//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuPG_Buildkit_Package_Lister {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GnuPG_Buildkit_Package_Lister.messages", typeof(messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extracting version informations... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string extract_version {
            get {
                return ResourceManager.GetString("extract_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generating the package list... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string generate_list {
            get {
                return ResourceManager.GetString("generate_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting the contents from the remote... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string get_remote {
            get {
                return ResourceManager.GetString("get_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string program_completed {
            get {
                return ResourceManager.GetString("program_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting program... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string program_starting {
            get {
                return ResourceManager.GetString("program_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL to fetch:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string url_fetch {
            get {
                return ResourceManager.GetString("url_fetch", resourceCulture);
            }
        }
    }
}
